<a href="https://colab.research.google.com/github/godrun666/2022winter-machinelearning-HW/blob/main/basic_usage_of_pytorch-tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 

**get** **started** ✈

In [3]:
x = torch.rand(5,3)
x

tensor([[0.9152, 0.2094, 0.2082],
        [0.8779, 0.4476, 0.9386],
        [0.6694, 0.7127, 0.1349],
        [0.9412, 0.6197, 0.8830],
        [0.7447, 0.7088, 0.1261]])

In [4]:
torch.cuda.is_available()

False

**tensor**

In [5]:
import numpy as np

In [6]:
#Directly from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)     #将np数组转化为 tensor
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [8]:
#From a NumPy array
x_np = torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [10]:
x2_np = torch.from_numpy(np_array)    #直接用tensor和用 from_numpy 函数 结果是一样的 都可以直接把np_array转换为tensor
x2_np

tensor([[1, 2],
        [3, 4]])

In [11]:
#From another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4440, 0.2635],
        [0.5864, 0.8496]]) 



In [12]:
#With random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)   #全部赋值为1 
zeros_tensor = torch.zeros(shape)  #全部赋值为0
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8716, 0.0776, 0.0888],
        [0.6075, 0.6887, 0.9260]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
#Attributes of a Tensor 
# shape  Datatype Device
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [4]:
#Operations on Tensors
#If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.
import torch
tensor = torch.rand(3,4)  #如果你将cpu切换为GPU 那么 数据将丢失 so 千万千万别在跑数据的时候用切换
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [5]:
tensor = torch.ones(4,4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:
#Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.
# See also torch.stack, another tensor joining op that is subtly different from torch.cat.
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
#求和
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [14]:
#改值
print(tensor, "\n")
tensor.add_(5)  #全部加5
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
